title:   Rain1106
description: A interesting blog
author: Siyu wang
avatar: /logo.png
email: 2998688414@qq.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
github:
  username: Siyu wang
  card: summary
logo: logo.png
social:
  name: Siyu wang
  links:
    - https://github.com/Rain1106-wang
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
